dataset_name: MY_DATASET

bag_list:

  - name: BAG_ID_1
    input_dir_location: /Volumes/MY_VOLUME/MY_DATASET
    bagfile: MY_DATASET.bag
    output_dir_location: /Volumes/MY_VOLUME/MY_DATASET/raw-ouputs

data_schema:

  - rosbag_topic: /husky/odom
    output_dir: odom
    output_type: csv
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/husky_velocity_controller/cmd_vel
    output_dir: velocity_control
    output_type: csv
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/husky_velocity_controller/cmd_vel_out
    output_dir: velocity_control_stamped
    output_type: csv
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/gps
    output_dir: gps
    output_type: csv
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/stereo_left/image_rect_color/compressed
    output_dir: img-front-stereo_left
    output_type: dir_of_imgs
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/stereo_right/image_rect_color/compressed
    output_dir: img-front-stereo_right
    output_type: dir_of_imgs
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/rear_center/image_rect_color/compressed
    output_dir: img-rear-center
    output_type: dir_of_imgs
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/forward/color/image_rect_color/compressed 
    output_dir: img-front-center
    output_type: dir_of_imgs
    start_idx: 0
    end_idx: -1
    throttle_rate: 1